@startuml
actor Client
participant website
participant GetAllProjectsActivity
database projects

Client -> website: access the website main page
website -> GetAllProjectsActivity: send get all projects request
GetAllProjectsActivity -> projects: load all projects
GetAllProjectsActivity <-- projects: all projects
website <-- GetAllProjectsActivity: List<ProjectModel>
Client <-- website: present a list of all projects
@enduml