@startuml
actor Client
participant website
participant GetProjectActivity
database projects

Client -> website: select a project to view more
website -> GetProjectActivity: send get project request
GetProjectActivity -> projects: load project
GetProjectActivity <-- projects: project
website <-- GetProjectActivity: ProjectModel
Client <-- website: present the project
@enduml